<?xml version="1.0"?>
<robot name="fourwheeler" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_with" value="1.75" />
  <xacro:property name="base_length" value="0.90" />
  <xacro:property name="base_height" value="0.60" />
  <xacro:property name="wheel_with" value="0.09" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_y_pos" value="${base_with/2 + wheel_with/2}" />
  <xacro:property name="wheel_x_pos" value="${base_length/2 - wheel_radius}" />
  <xacro:property name="lowride" value="${(base_height/2) * -1}" />
  <xacro:property name="lidar_radius" value="0.05" />
  <xacro:property name="hood_height" value="0.005" />
  
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_with} ${base_height}" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1" />
      </material>
    </visual>
  </link>
  
  <link name="base_footprint" />
  <joint name="base_footprint_to_base" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${-(lowride - wheel_radius)}" />
  </joint>
  
  <xacro:macro name="wheel" params="wheel_name reflect_y reflect_x">
  <link name="${wheel_name}">
    <visual>
      <geometry>
        <cylinder length="${wheel_with}" radius="${wheel_radius}" />
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
  </link>
  
  <joint name="${wheel_name}_to_base" type="continuous">
    <parent link="base_link" />
    <child link="${wheel_name}" />
    <origin xyz="${wheel_x_pos * reflect_x} ${wheel_y_pos * reflect_y} ${lowride}" rpy="1.57 0 0" />
    <axis xyz="0 0 1" />
  </joint>
  </xacro:macro>
  
  <xacro:wheel wheel_name="front_left_wheel" reflect_y="1" reflect_x="1"/>
  <xacro:wheel wheel_name="front_right_wheel" reflect_y="-1" reflect_x="1"/>
  <xacro:wheel wheel_name="rear_left_wheel" reflect_y="1" reflect_x="-1"/>
  <xacro:wheel wheel_name="rear_right_wheel" reflect_y="-1" reflect_x="-1"/>
  
  <link name="hood">
    <visual>
      <geometry>
        <box size="${base_length + 0.01} ${base_with + 0.01} ${hood_height}" />
      </geometry>
      <material name="yellow">
        <color rgba="0.8 0.8 0 1" />
      </material>
    </visual>
  </link>
  
  <joint name="hood_to_base" type="fixed">
    <parent link="base_link" />
    <child link="hood" />
    <origin xyz="0 0 ${base_height/2 + hood_height/2}" />
  </joint>
  
    <link name="lidar">
    <visual>
      <geometry>
        <cylinder length="0.08" radius="${lidar_radius}" />
      </geometry>
      <material name="gray">
        <color rgba="0.7 0 0 1" />
      </material>
    </visual>
  </link>
  
  <joint name="lidar_to_hood" type="continuous">
    <parent link="hood" />
    <child link="lidar" />
    <origin xyz="${base_length/2 - lidar_radius} 0 0.004" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>
  
</robot>
